export const SIDEMENU_TOGGLE = 'SIDEMENU_TOGGLE'
export const LOAD_COMPANIES = 'LOAD_COMPANIES'
export const LOAD_STOCKS = 'LOAD_STOCKS'
export const SELECT_COMPANY = 'SELECT_COMPANY'
export const LOAD_CATEGOTIES = 'LOAD_CATEGOTIES'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const PRODUCT_CATEGORY = 'PRODUCT_CATEGORY'
export const CATEGORY_COMPANY = 'CATEGORY_COMPANY'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const SELECT_STOCK = 'SELECT_STOCK'
export const SET_VIEW = 'SET_VIEW'
export const SET_CHART = 'SET_CHART'





